[theme]
base = "light"
primaryColor = "#1C1C1A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#1C1C1A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
