[theme]
base = "light"
primaryColor = "#0088b0"
backgroundColor = "#f3f2f2"
secondaryBackgroundColor = "#eae7e7"
textColor = "#201e1d"
font = "serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
